services:
  pwc.challenge.db:
    image: postgis/postgis:16-3.4-alpine
    volumes:
      - pwc.challenge.volume.postgres:/var/lib/postgresql/data/

  pwc.challenge.api:
    image: ${DOCKER_REGISTRY:-}pwcchallengeapi
    build:
      context: .
      dockerfile: PWC.Challenge.Api/Dockerfile
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

volumes:
  pwc.challenge.volume.postgres:
