services:
  pwc.challenge.azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: pwc.challenge.azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: always
    networks:
      - pwc_network
    volumes:
      - azurite-data:/data

  pwc.challenge.email.processor:
    image: ${DOCKER_REGISTRY:-}pwcchallengeemailprocessor
    container_name: pwc.challenge.email.processor
    build:
      context: .
      dockerfile: Email.Processor/Dockerfile
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://pwc.challenge.azurite:10000/devstoreaccount1;QueueEndpoint=http://pwc.challenge.azurite:10001/devstoreaccount1;TableEndpoint=http://pwc.challenge.azurite:10002/devstoreaccount1;
      - AzureFunctionsJobHost__extensions__durableTask__storageProvider__useLegacyPartitionManagement=true
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
    ports:
      - "7071:7071"
    depends_on:
      - pwc.challenge.azurite
    networks:
      - pwc_network

volumes:
  azurite-data:

networks:
  pwc_network:
    driver: bridge