version: '3.8'

services:
  pwc.challenge.db:
    image: postgis/postgis:16-3.4-alpine
    container_name: pwc.challenge.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PWChallenge
    ports:
      - "9432:5432"
    volumes:
      - pwc.challenge.volume.postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - pwc_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  pwc.challenge.redis:
    image: redis:7-alpine
    container_name: pwc.challenge.redis
    ports:
      - "9379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - pwc_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  pwc.challenge.azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: pwc.challenge.azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: always
    networks:
      - pwc_network
    volumes:
      - azurite-data:/data 
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data
    healthcheck:
      disable: true

  pwc.challenge.api:
    image: ${DOCKER_REGISTRY:-}pwcchallengeapi
    container_name: pwc.challenge.api
    build:
      context: .
      dockerfile: PWC.Challenge.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ApplicationDbContext=Server=pwc.challenge.db;Port=5432;Database=PWChallenge;User Id=postgres;Password=postgres;Include Error Detail=true;
      - ConnectionStrings__Redis=pwc.challenge.redis:6379
      - RedisSettings__InstanceName=PWChallenge
      - RedisSettings__AbsoluteExpirationInSeconds=30
      - RedisSettings__SlidingExpirationInSeconds=15
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__Port=587
      - EmailSettings__Username=your_email@gmail.com
      - EmailSettings__Password=your_app_password
    volumes:
      - type: bind
        source: ${APPDATA}/Microsoft/UserSecrets
        target: /home/app/.microsoft/usersecrets
        read_only: true
    depends_on:
      pwc.challenge.db:
        condition: service_healthy
      pwc.challenge.redis:
        condition: service_healthy
      pwc.challenge.azurite:
        condition: service_started
    ports:
      - "9080:8080"
      - "9081:8081"
    restart: always
    networks:
      - pwc_network
    healthcheck:
      disable: true
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  pwc.challenge.email.processor:
    image: ${DOCKER_REGISTRY:-}pwcchallengeemailprocessor
    container_name: pwc.challenge.email.processor
    build:
      context: .
      dockerfile: Email.Processor/Dockerfile
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://pwc.challenge.azurite:10000/devstoreaccount1;QueueEndpoint=http://pwc.challenge.azurite:10001/devstoreaccount1;TableEndpoint=http://pwc.challenge.azurite:10002/devstoreaccount1;
      - AzureWebJobsSecretStorageType=files
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ApplicationDbContext=Server=pwc.challenge.db;Port=5432;Database=PWChallenge;User Id=postgres;Password=postgres;Include Error Detail=true;
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__Port=587
      - EmailSettings__Username=your_email@gmail.com
      - EmailSettings__Password=your_app_password
    ports:
      - "7071:7071"
    depends_on:
      pwc.challenge.db:
        condition: service_healthy
      pwc.challenge.azurite:
        condition: service_started
      pwc.challenge.api:
        condition: service_started
    networks:
      - pwc_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7071/admin/host/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

volumes:
  pwc.challenge.volume.postgres:
  redis_data:
  azurite-data:

networks:
  pwc_network:
    driver: bridge