version: '3.8'

services:
  pwc.challenge.db:
    image: postgis/postgis:16-3.4-alpine
    container_name: pwc.challenge.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PWChallenge
    ports:
      - "9432:5432"
    volumes:
      - pwc.challenge.volume.postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - pwc_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  pwc.challenge.redis:
    image: redis:7-alpine
    container_name: pwc.challenge.redis
    ports:
      - "9379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - pwc_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  pwc.challenge.api:
    image: ${DOCKER_REGISTRY:-}pwcchallengeapi
    container_name: pwc.challenge.api
    build:
      context: .
      dockerfile: PWC.Challenge.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__ApplicationDbContext=Server=pwc.challenge.db;Port=5432;Database=PWChallenge;User Id=postgres;Password=postgres;Include Error Detail=true;
      - ConnectionStrings__Redis=pwc.challenge.redis:6379
      - RedisSettings__InstanceName=PWChallenge
      - RedisSettings__AbsoluteExpirationInSeconds=30
      - RedisSettings__SlidingExpirationInSeconds=15
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__Port=587
      - EmailSettings__Username=your_email@gmail.com
      - EmailSettings__Password=your_app_password
    volumes:
      - type: bind
        source: ${APPDATA}/Microsoft/UserSecrets
        target: /home/app/.microsoft/usersecrets
        read_only: true
    depends_on:
      pwc.challenge.db:
        condition: service_healthy
      pwc.challenge.redis:
        condition: service_healthy
    ports:
      - "9080:8080"
      - "9081:8081"
    restart: always
    networks:
      - pwc_network
    healthcheck:
      disable: true
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

volumes:
  pwc.challenge.volume.postgres:
  redis_data:

networks:
  pwc_network:
    driver: bridge
